version: 2.1
executors:
  docker-publisher:
    environment:
      PROJECT_NAME: tp-Team-3
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  lint-code:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # yarn install
      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  ##JOB
  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker # Ask circleci new Docker Engine to build outside of container
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/${PROJECT_NAME}:latest ./docker/nodejs/dockerfile --compress --force-rm --no-cache --pull
      - run:
          name: Archive nginx Docker image
          command: docker save -o ./${PROJECT_NAME}_image.tar $DOCKERHUB_USERNAME/${PROJECT_NAME}:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./${PROJECT_NAME}_image.tar

  ##JOB
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/${PROJECT_NAME}_image.tar
      # - run:
      #     name: Rename nginx Docker image
      #     command: docker tag docker_nginx mrzyro/ynov-devops-tp2-team-2_nginx:latest
      - run:
          name: Publish image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/${PROJECT_NAME}:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build-image:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build-image
          filters:
            branches:
              only: master