version: 2.1

#execution de l'image par le docker
executors:
  nodejs:
    docker:
      - image: circleci/node:12.14
jobs:
  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    # yarn install
    - run:
        name: Install Dependencies
        command: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}


workflows:
  myworkflow:
    jobs:
      - build
      - publish-latest:
          requires:
            - build