version: 2.1

#execution de l'image par le docker
executors:
  nodejs:
    docker:
      - image: circleci/node:12.14
jobs:
  install:
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  myworkflow:
    jobs:
      - build
      - publish-latest:
          requires:
            - build